## 00. pythorch fundamentals

Resource notebook: https://www.learnpytorch.io/

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cpu


## introduction to Tensor

##creating tensors

In [ ]:
# scaler
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
#VECTOR
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 3, 6],
                       [7, 3, 2],
                       [3, 0, 4]],
                       [[5, 4, 6],
                        [6, 4, 9],
                        [4, 4, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random tensors

Por que tensores randomicos?
é o melhor jeito de amplificar uma rede neural.
Se comeca uma rede com seus tensores randomicos, depois


In [6]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6673, 0.2777, 0.2868, 0.1580],
        [0.2286, 0.8080, 0.4419, 0.1573],
        [0.9930, 0.5961, 0.0293, 0.6081]])

In [4]:
#criando um tensor de dimensoes similares para imagens
random_image_size_tensor =  torch.rand(size=(3, 224, 224)) #hight, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### zeros and ones


In [7]:
#create a tensor of all zeros
zeros = torch.zeros(size =(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [8]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
#create a tensor with all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
ones.dtype

torch.float32

In [12]:
random_tensor.dtype

torch.float32

### creating a range of tensors and tensors-like

In [19]:
one_to_ten = torch.arange(start=1 , end= 11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatype

NOTE: tensor datatypes is one of the 3 big erros you`ll run into with PyThorch & deep learning:

    1. Tensors not right datatype
    2. Tensors not right shape
    3. Tensors not on the right device

In [57]:
# float 32 tensor
float_32_tensor = torch.tensor([3.54548415, 6.05421874, 9.0548451215],
                                 dtype=torch.int32, #what data type is the tensor (e.g. float32 or float16)
                                 device= None, #what divices is your tensor on like cuda
                                 requires_grad= False) #whether or not to track gradients with this tensors operations
float_32_tensor

C:\Users\fafap\AppData\Local\Temp\ipykernel_31572\3379230706.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  float_32_tensor = torch.tensor([3.54548415, 6.05421874, 9.0548451215],


tensor([3, 6, 9], dtype=torch.int32)

In [36]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3.0352, 6.4531, 9.2344], dtype=torch.float16)

In [37]:
float_32_tensor * float_16_tensor

tensor([ 9.2103, 41.6521, 85.2725])

In [59]:
ten_zeros.is_cuda

False

### getting information from tensors  (tensor attributes)

    1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
    2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
    3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [61]:
#create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.1983, 0.0915, 0.4899, 0.8419],
        [0.3537, 0.9102, 0.9597, 0.1196],
        [0.5429, 0.9438, 0.7373, 0.1724]])

In [68]:
#find out some details about some tensor
print(some_tensor)
print(f"data type of the tensor is {some_tensor.dtype}")
print(f"shape of the tensor is {some_tensor.shape}")
print(f"divice of the tensor is {some_tensor.device}")

tensor([[0.1983, 0.0915, 0.4899, 0.8419],
        [0.3537, 0.9102, 0.9597, 0.1196],
        [0.5429, 0.9438, 0.7373, 0.1724]])
data type of the tensor is torch.float32
shape of the tensor is torch.Size([3, 4])
divice of the tensor is cpu


### Manipulating Tensors (tensors operations)

Tensors operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [76]:
#create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [77]:
# multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [80]:
# subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [81]:
# try out pyTorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [83]:
print(tensor)

tensor([1, 2, 3])


### Matrix multiplication 

two main ways of performing muiltiplication in neural networks and deep leraning:

1. element-wise multiplication
2. Matrix multiplication
 more information on: https://www.mathsisfun.com/algebra/matrix-multiplying.html

there are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimations** must match:
* ` (3, 2) @ (3, 2)` wont work
* ` (2, 3) @ (3, 2)` will work
* ` (3, 2) @ (2, 3)` will work
2. the resulting matrix has the shape of the **outer dimensions**:
* ` (2, 3) @ (3, 2)` -> `(2, 2)`
* ` (3, 2) @ (2, 3)` -> `(3, 3)`

In [97]:
#this wont work for exemple
#torch.matmul(torch.rand(3, 2), torch.rand(3, 2))
# the resulting matrix has the shape of the **outer dimensions**
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.9723, 0.4191, 0.5391],
        [0.2307, 0.0968, 0.1806],
        [0.3289, 0.1456, 0.1047]])

In [85]:
# element-wise multiplication
print(tensor, "*", tensor)
print(f"Equal: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [86]:
# Matrix multiplication
torch.matmul(tensor, tensor) 

tensor(14)

In [87]:
# the same thing by hand is like
1*1 + 2*2 + 3*3

14

In [88]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 3.99 ms


In [91]:
%%time
tensor @ tensor

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [89]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common erros in deep leaning: shape errors 

In [98]:
Tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
Tensor_B = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]]) 

In [99]:
#gets a error becouse thoes not follow the rule fo Mul matrix
#torch.mm(Tensor_A, Tensor_B)  the same thing for writing torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

 To fix our tensor shape issues, we can  manipulate the shape of our tensor using a **transpose**

 A **tranpose** switches the axes or dimansions of a given tensor.

In [100]:
Tensor_B 

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [102]:
Tensor_B.T, Tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [109]:
# the matrix multplication operation works when Tensor_B is transpose
print(f"Original shape: Tensor_A = {Tensor_A.shape}, Tensor_B = {Tensor_B.shape}")
print(f"new shapes: Tensor_A = {Tensor_A.shape},(same shape as above) Tensor_B = {Tensor_B.T.shape}")
print(f"Multiplying: {Tensor_A.shape} @ {Tensor_B.shape} -> inner dimansions must match")
print(f"Output:\n")
Output = torch.mm(Tensor_A, Tensor_B.T)
print(Output)
print(f"Output shape: {Output.shape}")

torch.mm(Tensor_A, Tensor_B.T), torch.mm(Tensor_A, Tensor_B.T).shape

Original shape: Tensor_A = torch.Size([3, 2]), Tensor_B = torch.Size([3, 2])
new shapes: Tensor_A = torch.Size([3, 2]),(same shape as above) Tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) -> inner dimansions must match
Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Output shape: torch.Size([3, 3])


(tensor([[ 23,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]),
 torch.Size([3, 3]))

### Finding the min, max, mean, sum, etc(tensor aggregetion)

In [137]:
# create tensors
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [116]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [117]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [123]:
# find the mean note: the torch.mean() function requeires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [124]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### finding the positional min and max

In [138]:
x += 1

In [139]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [140]:
# find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurrs
x.argmin()

tensor(0)

In [141]:
x[0]

tensor(1)

In [142]:
x.argmax()

tensor(9)

In [143]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezsing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certing shape but keep the same memory
as the original 
* Stacking - combine multiples tensors on top of each other (vstack) or side by side
(hstack) 
* Squeeze - removes all `1` demensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [13]:
#create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [14]:
# adds an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [15]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [19]:
z[:, 0] = 9
x, z

(tensor([9., 2., 3., 4., 5., 9., 7., 8., 9.]),
 tensor([[9., 2., 3., 4., 5., 9., 7., 8., 9.]]))