## 00. pythorch fundamentals

Resource notebook: https://www.learnpytorch.io/

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cpu


## introduction to Tensor

##creating tensors

In [3]:
# scaler
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
#VECTOR
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
TENSOR = torch.tensor([[[1, 3, 6],
                       [7, 3, 2],
                       [3, 0, 4]],
                       [[5, 4, 6],
                        [6, 4, 9],
                        [4, 4, 4]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 3])

### Random tensors

Por que tensores randomicos?
é o melhor jeito de amplificar uma rede neural.
Se comeca uma rede com seus tensores randomicos, depois


In [15]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6753, 0.7574, 0.6176, 0.2695],
        [0.5249, 0.5818, 0.3401, 0.5643],
        [0.8287, 0.8834, 0.8997, 0.7812]])

In [16]:
#criando um tensor de dimensoes similares para imagens
random_image_size_tensor =  torch.rand(size=(3, 224, 224)) #hight, width, colour channels (R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### zeros and ones


In [17]:
#create a tensor of all zeros
zeros = torch.zeros(size =(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
#create a tensor with all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
ones.dtype

torch.float32

In [21]:
random_tensor.dtype

torch.float32

### creating a range of tensors and tensors-like

In [22]:
one_to_ten = torch.arange(start=1 , end= 11,step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatype

NOTE: tensor datatypes is one of the 3 big erros you`ll run into with PyThorch & deep learning:

    1. Tensors not right datatype
    2. Tensors not right shape
    3. Tensors not on the right device

In [24]:
# float 32 tensor
float_32_tensor = torch.tensor([3.54548415, 6.05421874, 9.0548451215],
                                 dtype=torch.int32, #what data type is the tensor (e.g. float32 or float16)
                                 device= None, #what divices is your tensor on like cuda
                                 requires_grad= False) #whether or not to track gradients with this tensors operations
float_32_tensor

C:\Users\fafap\AppData\Local\Temp\ipykernel_34828\3379230706.py:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  float_32_tensor = torch.tensor([3.54548415, 6.05421874, 9.0548451215],


tensor([3, 6, 9], dtype=torch.int32)

In [25]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [26]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

In [27]:
ten_zeros.is_cuda

False

### getting information from tensors  (tensor attributes)

    1. Tensors not right datatype - to get datatype from a tensor, can use `tensor.dtype`
    2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
    3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [28]:
#create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5832, 0.1716, 0.9896, 0.6924],
        [0.9332, 0.5969, 0.6488, 0.1037],
        [0.6804, 0.2720, 0.9878, 0.2834]])

In [29]:
#find out some details about some tensor
print(some_tensor)
print(f"data type of the tensor is {some_tensor.dtype}")
print(f"shape of the tensor is {some_tensor.shape}")
print(f"divice of the tensor is {some_tensor.device}")

tensor([[0.5832, 0.1716, 0.9896, 0.6924],
        [0.9332, 0.5969, 0.6488, 0.1037],
        [0.6804, 0.2720, 0.9878, 0.2834]])
data type of the tensor is torch.float32
shape of the tensor is torch.Size([3, 4])
divice of the tensor is cpu


### Manipulating Tensors (tensors operations)

Tensors operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [30]:
#create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10


tensor([11, 12, 13])

In [31]:
# multiply tensor by 10
tensor * 10


tensor([10, 20, 30])

In [32]:
# subtract tensor by 10
tensor - 10

tensor([-9, -8, -7])

In [33]:
# try out pyTorch in-build functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [34]:
print(tensor)

tensor([1, 2, 3])


### Matrix multiplication 

two main ways of performing muiltiplication in neural networks and deep leraning:

1. element-wise multiplication
2. Matrix multiplication
 more information on: https://www.mathsisfun.com/algebra/matrix-multiplying.html

there are two main rules that performing matrix multiplication needs to satisfy:
1. the **inner dimations** must match:
* ` (3, 2) @ (3, 2)` wont work
* ` (2, 3) @ (3, 2)` will work
* ` (3, 2) @ (2, 3)` will work
2. the resulting matrix has the shape of the **outer dimensions**:
* ` (2, 3) @ (3, 2)` -> `(2, 2)`
* ` (3, 2) @ (2, 3)` -> `(3, 3)`

In [35]:
#this wont work for exemple
#torch.matmul(torch.rand(3, 2), torch.rand(3, 2))
# the resulting matrix has the shape of the **outer dimensions**
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.4538, 0.8553, 0.7276],
        [0.5592, 0.9503, 0.7746],
        [0.3173, 0.4910, 0.3827]])

In [36]:
# element-wise multiplication
print(tensor, "*", tensor)
print(f"Equal: {tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equal: tensor([1, 4, 9])


In [37]:
# Matrix multiplication
torch.matmul(tensor, tensor) 

tensor(14)

In [38]:
# the same thing by hand is like
1*1 + 2*2 + 3*3

14

In [39]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: total: 0 ns
Wall time: 3.99 ms


In [40]:
%%time
tensor @ tensor

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

In [41]:
%%time
torch.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 0 ns


tensor(14)

### One of the most common erros in deep leaning: shape errors 

In [42]:
Tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
Tensor_B = torch.tensor([[7, 8],
                        [9, 10],
                        [11, 12]]) 

In [43]:
#gets a error becouse thoes not follow the rule fo Mul matrix
#torch.mm(Tensor_A, Tensor_B)  the same thing for writing torch.matmul()

 To fix our tensor shape issues, we can  manipulate the shape of our tensor using a **transpose**

 A **tranpose** switches the axes or dimansions of a given tensor.

In [44]:
Tensor_B 

tensor([[ 7,  8],
        [ 9, 10],
        [11, 12]])

In [45]:
Tensor_B.T, Tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [46]:
# the matrix multplication operation works when Tensor_B is transpose
print(f"Original shape: Tensor_A = {Tensor_A.shape}, Tensor_B = {Tensor_B.shape}")
print(f"new shapes: Tensor_A = {Tensor_A.shape},(same shape as above) Tensor_B = {Tensor_B.T.shape}")
print(f"Multiplying: {Tensor_A.shape} @ {Tensor_B.shape} -> inner dimansions must match")
print(f"Output:\n")
Output = torch.mm(Tensor_A, Tensor_B.T)
print(Output)
print(f"Output shape: {Output.shape}")

torch.mm(Tensor_A, Tensor_B.T), torch.mm(Tensor_A, Tensor_B.T).shape

Original shape: Tensor_A = torch.Size([3, 2]), Tensor_B = torch.Size([3, 2])
new shapes: Tensor_A = torch.Size([3, 2]),(same shape as above) Tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) -> inner dimansions must match
Output:

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])
Output shape: torch.Size([3, 3])


(tensor([[ 23,  29,  35],
         [ 53,  67,  81],
         [ 83, 105, 127]]),
 torch.Size([3, 3]))

### Finding the min, max, mean, sum, etc(tensor aggregetion)

In [47]:
# create tensors
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [48]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [49]:
# find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [50]:
# find the mean note: the torch.mean() function requeires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [51]:
# find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### finding the positional min and max

In [52]:
x += 1

In [53]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [54]:
# find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurrs
x.argmin()

tensor(0)

In [55]:
x[0]

tensor(1)

In [56]:
x.argmax()

tensor(9)

In [57]:
x[9]

tensor(91)

### Reshaping, stacking, squeezing and unsqueezsing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certing shape but keep the same memory
as the original 
* Stacking - combine multiples tensors on top of each other (vstack) or side by side
(hstack) 
* Squeeze - removes all `1` demensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [2]:
#create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [3]:
# adds an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [4]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [5]:
# changing z changes x (becouse a view of a tensor shares the same memoryas the original input)
z[:, 0] = 9
x, z

(tensor([9., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [6]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 2., 3., 4., 5., 6., 7., 8., 9.],
        [9., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [7]:
# hstack view the horizontal witch means that dim = 1
x_stacked = torch.hstack([x, x, x, x])
x_stacked

tensor([9., 2., 3., 4., 5., 6., 7., 8., 9., 9., 2., 3., 4., 5., 6., 7., 8., 9.,
        9., 2., 3., 4., 5., 6., 7., 8., 9., 9., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# remove extra demensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[9., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([9., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [9]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# add a extra dimention with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1) #can change to dim=1 to see what happens
print(f"\nNew tensor: {x_unsqueezed}")
print(f"new shape: {x_unsqueezed.shape}")

Previous target: tensor([9., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[9.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
new shape: torch.Size([9, 1])


In [12]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height, width, colour_channels]

#permute the original tensor to rearrange the axis (or dem) order
x_permuted = x_original.permute(2, 0, 1) #s shift eaxis 0 -> 1, 1 -> 2, 2 -> 0
print(f"previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour_channels, hight, width]

previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [13]:
x_original[0, 0, 0] = 45346
x_original[0, 0, 0], x_permuted[0, 0, 0] #will be the same becouse they share the same memory

(tensor(45346.), tensor(45346.))

## Indexing (selecting data from tensors)

indexing with pyTorch is similar to indexing with numPy

In [16]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [18]:
# index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [27]:
print(x[0, 0]) # just the middle part, can also write x[0][0][0]
print(x[0, 0, 0]) #just the firt number, can also write x[0][0][0]


tensor([1, 2, 3])
tensor(1)
tensor(9)


In [36]:
# can also use ":" to select "all" of the target dimesion
print(x[0, 0, 1:]) # you can read this like select 1>= 
print(x[0, 0, :2]) # can also read this as select 2 <=

tensor([2, 3])
tensor([1, 2])


In [38]:
# get all the elements from the frist and second dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [40]:
#index to reaturn 9
print(x[0][2][2]) # last number also 9

#index to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


### PyTorch tensors & NumPy

numPy is a popular scientific python numerical computing library

and because of this, pytorch has functionality to interact with it

* data in NumPy, want in pyTorch tensor -> `torch.from_numpy(ndarry)`
* PyTroch tensor -> NumPy -> `torch.Tensor.numpy()` 

In [47]:
#numpy arroy to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch reflects numpy`s default datatype of float64 unless specifield otherwise ".type(torch.float32)"
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [48]:
# change the value of array, will keep theis to the tensor?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [49]:
# tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [51]:
#change the tensor, will reflects to numpy tensor?

tensor = tensor + 1
numpy_tensor, tensor

(array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 tensor([2., 2., 2., 2., 2., 2., 2.]))

## reproducbility (trying to take the random out of random)

in short how a neural network learns:

`starts with random numbers -> tensor operations -> update random numbers to try and make`
`they bettter representations of the data -> again -> again -> again...`

to reduce the randomness in neural networks and pytorch comes the concept fo **random seed**

Essentially what the random seed works is "flavour" the randomness.

In [4]:
import torch

# create two random tensors
Random_Tensor_A = torch.rand(3, 4)
Random_Tensor_B = torch.rand(3, 4)

print(Random_Tensor_A)
print(Random_Tensor_B)

tensor([[0.3078, 0.6585, 0.2221, 0.4092],
        [0.3125, 0.7066, 0.9661, 0.8152],
        [0.3557, 0.5672, 0.2842, 0.4304]])
tensor([[0.9195, 0.6745, 0.0994, 0.7964],
        [0.8904, 0.2058, 0.1266, 0.0750],
        [0.5422, 0.2870, 0.7395, 0.3400]])


## Running tensors and PyTorch objects on the GPUs (and make faster computations)

GPUs = faster computation on numbers, thanks to CUDA + Nvidea hardware + pytorch working behind the scenes to make everything hunky dory (good)

### 1. getting a GPU

1. Easiest - use Goggle colab for a free GPU (options to upgrade as well)
2. Use your own GPU - a little bit of setup and requires the investment of purchusing a GPU, there`s lots of options 

In [15]:
import torch

torch.cuda.is_available()

False

In [18]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [1]:
import argparse
import torch

# Função para criar um objeto 'args' com base nos argumentos passados
def create_args(disable_cuda):
    args = argparse.Namespace()
    args.disable_cuda = disable_cuda
    args.device = None
    if not args.disable_cuda and torch.cuda.is_available():
        args.device = torch.device('cuda')
    else:
        args.device = torch.device('cpu')
    return args

# Passando o argumento 'disable_cuda' como False (usar GPU) ou True (usar CPU)
disable_cuda = False  # Defina como True ou False para habilitar ou desabilitar a GPU
args = create_args(disable_cuda)
print(args.device)  # Aqui você verá se está usando a GPU ou a CPU


cpu


CPU sendo usada
